//const mongoClient = require('mongodb').MongoClient;
const {MongoClient, ObjectID} = require('mongodb');

var obj = new ObjectID();

console.log('obj is here',obj);

var user = { 
    name: 'lowolfne',
    age: 25
};

var {name} = user;

console.log(name);

MongoClient.connect( 'mongodb://localhost:27017/TodoApp', (err, client) => {

    if(err) {
        console.log('Unable to connect to MongoDB server');
    }
    else {
        console.log('Connected to MongoDB server');
    
        // the _id or object id
        // -generated by mongodb
        // -format is timestamp, device id, process id, random

        const db = client.db('TodoApp');
        db.collection('Users').insertOne({
            //_id: 5,
            name: 'Morty',
            age: 16,
            location: 'Earth'
        }, (err, result) => {
            if ( err ){
                return console.log('Unable to insert todo', err);
            }
    
            console.log(JSON.stringify(result.ops, undefined, 2));
            console.log(result.ops[0]._id);
        });
    
        client.close();
    }
});


//const db = client.db('TodoApp');
// db.collection('Todos').insertOne({
//     text: 'Something to do',
//     completed: false
// }, (err, result) => {
//     if ( err ){
//         return console.log('Unable to insert todo', err);
//     }

//     console.log(JSON.stringify(result.ops, undefined, 2));
// });
// if(err) {
//     return console.log('Unable to connect to MongoDB server');
// }

// console.log('Connected to MongoDB server');

//db.close();